version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: my-mongo
    ports:
      - "30000:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_DATABASE: filmsdb

volumes:
  mongo-data:
